version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8000:8001"
    environment:
      - PYTHONUNBUFFERED=1
    pull_policy: build
