version: '3.8'

services:
  slc-roboticas:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:81"
    command: >
      sh -c "python manage.py runserver"
    pull_policy: build
