version: '3'

services:
  slc-roboticas:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 10.0.0.8:8000"
    pull_policy: build
