# Generated by Django 4.1.5 on 2023-01-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientemodel_delete_clietemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteModel',
            new_name='Client',
        ),
    ]
